### ISSUE TITLE
Any tips on: How to show numeric key-board on iOS together with npm module for currency format?

### ISSUE THREAD

**Issue by Ross1307** [cloudfour/pwastats#168]
### 
Can anybody recommend a certain PWA web development Github or Slack channel where I can post issues? 

I'm finding trouble with: 
How to show numeric key-board on iOS together with npm module for currency format.

**Comment by calebeby** [comment]
Try [Stack Overflow](https://stackoverflow.com)

**Comment by grigs** [comment]
FWIW, I worked with Brad Frost and Chris Coyier a few years ago to try to figure out to trigger the number keypad on iOS. Brad wrote up our findings here:
http://bradfrost.com/blog/post/better-numerical-inputs-for-mobile-forms/

Things may have changed since then. I haven't kept up to date on how iOS is handling it.

**Comment by Ross1307** [comment]
> Try [Stack Overflow](https://stackoverflow.com)

Yes it's already on there...but no working solutions or answers. I will check Jason's links. Cheers!
