### ISSUE TITLE
Building a Fast Progressive Web Application (PWA) With JAMstack

### ISSUE THREAD

**Issue by CookieDuster** [cloudfour/pwastats#186]
> **Note:** This template is for new case study content submissions only.
Feel free to replace the outline below if you are submitting a general issue instead.

---

### Summary

While building a PWA for a client we opted out for JAMstack to keep content as much as possible in the headless CMS, use JavaScript on the front-end and back-end, and minimize hosting costs.

### Source

e.g. https://bejamas.io/blog/jamstack-pwa/

### Tags

- jamstack
- performance

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by tylersticka** [comment]
@CookieDuster Thank you for your submission.

This article appears to be a general case study that does not link to a specific product or client. Because of that, I'm not certain that it's a very good fit for this directory.

If you refer to [other stories we've featured](https://www.pwastats.com/), you'll see that they always involve a specific product, company or service, a statistic, and a link to a source.

Feel free to re-open this issue if the story is updated with more specifics.

**Comment by CookieDuster** [comment]
Understood. Thx.
