### ISSUE TITLE
PWA Store

### ISSUE THREAD

**Issue by mattruddy** [cloudfour/pwastats#203]
> **Note:** This template is for new case study content submissions only.
Feel free to replace the outline below if you are submitting a general issue instead.

---

### Summary

PWA Store is a platform to discover and upload Progressive Web Apps which pass Google Lighthouse Report.

### Source

https://chromeunboxed.com/pwa-store-sets-its-sights-on-making-web-apps-easier-to-find/

### Tags

- PWA
- React
- App Development

_List all that apply from the [tags directory](https://github.com/cloudfour/pwastats/tree/master/_tags)._

**Comment by tylersticka** [comment]
Thanks for your submission, @mattruddy. Unfortunately we can't accept it because it does not include any stats.

The purpose of this project is to consolidate different PWA-related performance metrics in a single place so those evaluating PWAs can get a sense of their real-world relevance. Your submission includes a third-party source, which is great, but its content isn't consistent with what [what we've already featured](https://www.pwastats.com/), which is why we can't accept it.
