### ISSUE TITLE
Are the block links accessible?

### ISSUE THREAD

**Issue by emersonthis** [cloudfour/pwastats#205]
It's my understanding that large "block links" (components wrapped in an `<a>` tag) can be problematic for accessibility (and usability) reasons. 

[This article](https://adrianroselli.com/2020/02/block-links-cards-clickable-regions-etc.html
) talks about this concern. [Inclusive components](https://inclusive-components.design/cards/) echos some of those concerns, and offers mitigation strategies.

**Comment by tylersticka** [comment]
The block links are accessible, but they could be _more_ accessible.

As is, the content of block links is likely to be read aloud as a run-on sentence consisting of the visually hidden heading and the paragraph that follows. Thankfully, the secondary links and meta information are separate elements and will _not_ be read aloud in the same manner.

The main issue is that those headings are not navigable on their own. Since they are visually hidden, a very quick and easy fix would be to move those headings _out_ of the anchor (but still nested within the `<article>` element).

(In the future, this pattern will be revised entirely. See: https://github.com/cloudfour/cloudfour.com-patterns/issues/493)

**Comment by tylersticka** [comment]
Closing this since the original question has been answered and there's an eventual plan for moving forward.
