### ISSUE TITLE
Tiles are in different order than current production site

### ISSUE THREAD

**Issue by megnotarte** [cloudfour/pwastats#214]
I noticed that the tiles are ordered differently on the preview site as compared to production. Look at the Commonfloor tile for example. 
![order](https://user-images.githubusercontent.com/66242/86949872-2bf92680-c104-11ea-9274-ac2c873323f2.gif)

Is this expected? If not, is it acceptable?

**Comment by emersonthis** [comment]
This is expected / discussed with @tylersticka. On both versions, the posts appear in reverse chronological order, but Eleventy and Jekyll's ordering algorithm(s) differ subtly in how they handle "a tie" between two posts that were published on the same date. The overall ordering _should_ be the same outside of these instances. It's not obvious at-a-glance because we don't print the publication dates onto the page. But you can verify by looking at the filenames in the source code, which are prefixed with a date. There's [a few instances](https://github.com/cloudfour/pwastats/commit/a5b8a84a6beca755c47af172106bd9116f29a9f4) where several stats were published together on the same day.

Please reopen if you see anything that's inconsistent with this explanation.
