### ISSUE TITLE
Atom Feed -> Twitter IFTTT doesn't seem to be working

### ISSUE THREAD

**Issue by gerardo-rodriguez** [cloudfour/pwastats#98]
A new post was added today, but no tweet was posted.

New post: https://www.pwastats.com/2017/04/voot/
Nothing on Twitter: https://mobile.twitter.com/PWAStats
The IFTTT applet here: https://ifttt.com/my_applets

**Comment by erikjung** [comment]
After checking the applet (clicking the "Check now" button), it ran successfully.

<img width="408" alt="screen shot 2017-04-24 at 12 02 11 pm" src="https://cloud.githubusercontent.com/assets/61204/25353943/eb731b34-28e5-11e7-90f7-08453ce9c698.png">

It might have just been delayed (since the post was added less than an hour ago).
